services:
  website:
    image: website:latest
    ports:
      - "8080:8080"
    environment:
      - GITHUB_CLIENT_ID=fill
      - GITHUB_CLIENT_SECRET=fill
      - ASPNETCORE_ENVIRONMENT=fill
      - DOTNET_ENVIRONMENT=fill
      
    volumes:
      - ./images:/app/wwwroot/images/
      - ./data:/app/wwwroot/data/