services:
  website:
    image: website
    build:
      context: .
      dockerfile: website/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./content/images:/app/wwwroot/images
      - ./content/data:/app/wwwroot/data
    environment:
      - DOTNET_ENVIRONMENT=Production
